### ISSUE TITLE
Server Error

### ISSUE THREAD

**Issue by anas-yousef** [eclipse-pdt/pdt#99] opened 2021-02-03 21:40 UTC
**Describe the bug**

**Describe the eclipse environment**
A clear and concise description about Eclipse Version (ex. 2020-03), PDT version (7.0, 7.2) and installed additional plugins (PyDev, Symfony, Doctrine)

**Describe your system**
 - PHP Version (if related)
 - Webserver Version (if related)
 - Utilis (composer, php unit, Xdebug etc...)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by anas-yousef** [comment] 2021-02-03 21:47
Hello all, 
I just downloaded Eclipse IDE for PHP (2020-12) and everything went well.
I also downloaded PHP 8.0.2, I am using Windows 10.
I have a problem setting up the PHP Built-In Server. I followed the correct instructions,
and when I want to configure my resources to run on the server, I get this error:
"The server does not support version 7.4 of the PHP Project Specification"
![Screenshot 2021-02-03 234628](https://user-images.githubusercontent.com/44998563/106813732-12a86080-667a-11eb-9079-9850bcdbca31.png)
I would really appreciate it if someone can help me.
Thank You!

**Comment by mostafabarmshory** [comment] 2021-02-08 01:39
The PDT 8 is not stable.
You'd better use 7.x

**Comment by ibakirov** [comment] 2021-07-14 10:25
@anas-yousef take a look for workaround at #112

**Comment by agmckee** [comment] 2021-12-16 14:37
This was resolved by #63. This issue can be closed @zulus, it is a duplicate of #112 anyway.

**Closed** 2023-07-03 15:34 UTC
Labels: bug
